### ISSUE TITLE
Contact links have no href value

### ISSUE THREAD

**Issue by simonswiss** [claudiovallejo/portfolio#2]
Super nice website, congrats!

Just a quick heads up: the footer section in the homepage should, I assume, link to your twitter / dribble / github profiles. These links do not have a value in the `href` attribute, so on click it just brings users to the top of the page.

![image](https://cloud.githubusercontent.com/assets/485747/22284950/bc0ed2d6-e33d-11e6-9838-3f1569223168.png)

**Comment by claudiovallejo** [comment]
Thank you @simonswiss!

You're right... the contact links should link to their respective sites/form of contact. Really appreciate you taking the time to submit the issue. It should be working fine now :)

### Fix Reference
`index.html.erb` line 162—
Changed `href="<%= link.path %>"` => `href="<%= link.source %>"`.
